package com.pej.domains;
// Generated 30 oct. 2016 22:13:12 by Hibernate Tools 5.2.0.Beta1


import java.io.Serializable;
import java.util.*;

import javax.persistence.*;

import com.pej.annotations.ExcelCell;
import com.pej.domains.Formateur;
import com.pej.domains.Formationbeneficaire;
import com.pej.domains.Typeformation;

import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * Formation generated by hbm2java
 */
@Entity
@Table(name = "BILAN")
public class Bilan implements Serializable {

	private Integer idbilan;
	private String lieuformation;
	private Integer nbHommeAttendu;
	private Integer nbHommePresent;
	private Integer nbHommeAbsent;
	private Integer nbFemmeAttendu;
	private Integer nbFemmePresent;
	private Integer nbFemmeAbsent;
	private Integer nbNourice;
	private Integer nbAttendu;
	private Formation formation;
//	private Cooperative cooperative;
	private String dateformation;
		
	public Bilan() {
	}

	
	
    @Id
  	@GeneratedValue(generator = "SEQ_IDBILAN", strategy = GenerationType.SEQUENCE)
  	@SequenceGenerator(name = "SEQ_IDBILAN", sequenceName = "SEQ_IDBILAN",allocationSize=1)
    @Column(name="IDBILAN", unique=true, nullable=false, precision=22, scale=0)
	public Integer getIdbilan() {
		return idbilan;
	}

	public void setIdbilan(Integer idbilan) {
		this.idbilan = idbilan;
	}

	public String getLieuformation() {
		return lieuformation;
	}

	public void setLieuformation(String lieuformation) {
		this.lieuformation = lieuformation;
	}
	@Column(name="nbHommeAttendu")
	public Integer getNbHommeAttendu() {
		return nbHommeAttendu;
	}

	public void setNbHommeAttendu(Integer nbHommeAttendu) {
		this.nbHommeAttendu = nbHommeAttendu;
	}
	@Column(name="nbHommePresent")
	public Integer getNbHommePresent() {
		return nbHommePresent;
	}

	public void setNbHommePresent(Integer nbHommePresent) {
		this.nbHommePresent = nbHommePresent;
	}
	@Column(name="nbHommeAbsent")
	public Integer getNbHommeAbsent() {
		return nbHommeAbsent;
	}
	@Column(name="nbHommePresent")
	public void setNbHommeAbsent(Integer nbHommeAbsent) {
		this.nbHommeAbsent = nbHommeAbsent;
	}
	@Column(name="nbFemmeAttendu")
	public Integer getNbFemmeAttendu() {
		return nbFemmeAttendu;
	}

	public void setNbFemmeAttendu(Integer nbFemmeAttendu) {
		this.nbFemmeAttendu = nbFemmeAttendu;
	}
	@Column(name="nbFemmePresent")
	public Integer getNbFemmePresent() {
		return nbFemmePresent;
	}

	public void setNbFemmePresent(Integer nbFemmePresent) {
		this.nbFemmePresent = nbFemmePresent;
	}
	@Column(name="nbFemmeAbsent")
	public Integer getNbFemmeAbsent() {
		return nbFemmeAbsent;
	}

	public void setNbFemmeAbsent(Integer nbFemmeAbsent) {
		this.nbFemmeAbsent = nbFemmeAbsent;
	}
	@Column(name="nbNourice")
	public Integer getNbNourice() {
		return nbNourice;
	}

	public void setNbNourice(Integer nbNourice) {
		this.nbNourice = nbNourice;
	}
	@Column(name="nbAttendu")
	public Integer getNbAttendu() {
		return nbAttendu;
	}

	public void setNbAttendu(Integer nbAttendu) {
		this.nbAttendu = nbAttendu;
	}
	
	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDFORMATION")
	public Formation getFormation() {
		return formation;
	}

	public void setFormation(Formation formation) {
		this.formation = formation;
	}
	
//	@ManyToOne(fetch=FetchType.LAZY)
//    @JoinColumn(name="IDCOOPERATIVE")
//	public Cooperative getCooperative() {
//		return cooperative;
//	}
//
//	public void setCooperative(Cooperative cooperative) {
//		this.cooperative = cooperative;
//	}

	@Column(name = "DATEFORMATION", length = 255)
	public String getDateformation() {
		return this.dateformation;
	}

	public void setDateformation(String dateformation) {
		this.dateformation = dateformation;
	}

    



	
   


}
